marwin1991/profile-technology-icons

README.md

This PR is inspired by @Johanp77 
Thanks 👍🏼

Added UIUX section with Figma, MD, MUI and Firebase to web dev

---

README.md

This PR is inspired by @codeboyfriend 
Closes #2 
Thanks 👍🏼

Added Chakara UI, Atom, Sublime Text, Ant Design

---

README.md

Inspired by @MatheusAraujoSouza
After merge you can test it here: https://marwin1991.github.io/profile-technology-icons/

Added fortran

---

README.md

Inspired by @NoodleSushi
Thank you!
You can check it out, and if you miss any tech feel free to create issue :)

Added game dev section, unity and godot

---

README.md

added Databricks

---

README.md

- Fixed spelling of 'technologies' correctly in `README.md`
- Formatted `README.md`
- Fixed link of 'Operating Systems'

Miscellaneous fixes to README.md

---

README.md

Closes #110 
Thank you @Haris-Ali007

Added AI section and tensorFlow icon

---

src/pages/generator.js

This PR adds the functionality for formatting icons in a table. 
- Maximum number of columns is 8. Another row is added in case more than eight skills are selected.
- Maximum allowed size of icons if fixed to 50px if table mode is selected. Larger images tend to squish.
- Refactored generate function for simplification.

Icons as Table

---

README.md

Added Puppeteer icon to README.md in section of testing.
@marwin1991 please check this out and merge if its okay.

Added Puppeteer icon to README.md

---

README.md

Split adding issue to separate paragraph.
Added more wide description about adding an icon.

Updated Contribution part in README.md

---

README.md

Reverts marwin1991/profile-technology-icons#187

Revert "Added Realm icon to README.md"

---

README.md

@marwin1991 now you can close issue #193

Added Neovim icon to README.md

---

README.md

@marwin1991 I've fixed it. Now it 400x400px. Check if it's okay.

Added edited wxWidgets icon

---

README.md

@marwin1991 I've added new section, check if it's relevant and if so, please, add link to this section in readme.md header

Added Apache section and Solr icon to Readme.md

---

README.md

added Laravel

---

README.md

3 new icons.
1. **php (elephpant):**
2. **Linux:**
3. **RPG Maker:**

Linux, RPG Maker and a new PHP logo.

---

README.md

@marwin1991  Hi, added Hadoop to the Java-section but I'm not sure where it should go: Java or Database?

Added Hadoop icon to README.md

---

README.md

added Playwright

---

README.md

one more time thank you for your suggestion @FleetAdmiralJakob

added tRCP

---

README.md

Added dark star history graph

---

README.md

Closes #315
@Shabari02 thank you so much for your input and I'm sorry it took so long

Added puppet icon to devops section

---

README.md

added styled-components

---

README.md

Added Icons: 
Digital Ocean Cloud
Kali Linux 
Coral.ai (Google)
Raspberry Pi

Update README.md with new Icons

---

README.md

shadcn ui icon added

---

README.md

Shadcn UI icon added.
https://ui.shadcn.com/

New Icon - Shadcn UI

---

README.md

- Solidity
- Solana
- Hardhat
- Foundry
- Metamask
- Ethereum

Added blockchain domain icons

---

README.md

added jboss and wildfly

---

README.md

feat: add pycharm

---

README.md

1. Add new entries to the list of contents
- 📚 Bibliography managers
- 🔌 Microcontrollers
- 🛜️ MQTT technologies
2. Fix Netbeans icon's filename

Fix list of contents and icon url
